prisma:info Starting a postgresql pool with 13 connections.
prisma:info Started http server on http://127.0.0.1:34627
SELECT "public"."Board"."id", "public"."Board"."createdAt", "public"."Board"."updatedAt", "public"."Board"."title" FROM "public"."Board" WHERE "public"."Board"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."Thread"."id", "public"."Thread"."createdAt", "public"."Thread"."updatedAt", "public"."Thread"."bumpedAt", "public"."Thread"."title", "public"."Thread"."boardId", "public"."Thread"."rootPostId", "public"."Thread"."views", "public"."Thread"."sticky", "public"."Thread"."anchored", "public"."Thread"."locked", "public"."Thread"."cycle", "public"."Thread"."archived", "public"."Thread"."willArchive", "aggr_selection_0_Post"."_aggr_count_posts" FROM "public"."Thread" LEFT JOIN (SELECT "public"."Post"."threadId", COUNT(*) AS "_aggr_count_posts" FROM "public"."Post" GROUP BY "public"."Post"."threadId") AS "aggr_selection_0_Post" ON ("public"."Thread"."id" = "aggr_selection_0_Post"."threadId") WHERE "public"."Thread"."boardId" = $1 ORDER BY "public"."Thread"."sticky" DESC, "public"."Thread"."bumpedAt" DESC LIMIT $2 OFFSET $3
SELECT "public"."Post"."id", "public"."Post"."sage", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."createdAt", "public"."Post"."bodyHtml", "public"."Post"."bannedForThisPost", "public"."Post"."threadId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" IN ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) OFFSET $11
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25) OFFSET $26
SELECT "public"."_PostOnPost"."A", "public"."_PostOnPost"."B" FROM "public"."_PostOnPost" WHERE "public"."_PostOnPost"."A" IN ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."updatedAt", "public"."Post"."ipAddress", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."bodyHtml", "public"."Post"."bodyMd", "public"."Post"."bannedForThisPost", "public"."Post"."sage", "public"."Post"."threadId", "public"."Post"."rootPostId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1,$2,$3) OFFSET $4
2 / 3
SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."updatedAt", "public"."Post"."ipAddress", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."bodyHtml", "public"."Post"."bodyMd", "public"."Post"."bannedForThisPost", "public"."Post"."sage", "public"."Post"."threadId", "public"."Post"."rootPostId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1,$2,$3) OFFSET $4
3 / 3
SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."updatedAt", "public"."Post"."ipAddress", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."bodyHtml", "public"."Post"."bodyMd", "public"."Post"."bannedForThisPost", "public"."Post"."sage", "public"."Post"."threadId", "public"."Post"."rootPostId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1,$2,$3) OFFSET $4
1 / 3
SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."updatedAt", "public"."Post"."ipAddress", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."bodyHtml", "public"."Post"."bodyMd", "public"."Post"."bannedForThisPost", "public"."Post"."sage", "public"."Post"."threadId", "public"."Post"."rootPostId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1,$2,$3,$4) OFFSET $5
0 / 4
SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."updatedAt", "public"."Post"."ipAddress", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."bodyHtml", "public"."Post"."bodyMd", "public"."Post"."bannedForThisPost", "public"."Post"."sage", "public"."Post"."threadId", "public"."Post"."rootPostId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1) OFFSET $2
1 / 1
SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."updatedAt", "public"."Post"."ipAddress", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."bodyHtml", "public"."Post"."bodyMd", "public"."Post"."bannedForThisPost", "public"."Post"."sage", "public"."Post"."threadId", "public"."Post"."rootPostId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1) OFFSET $2
0 / 1
SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."updatedAt", "public"."Post"."ipAddress", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."bodyHtml", "public"."Post"."bodyMd", "public"."Post"."bannedForThisPost", "public"."Post"."sage", "public"."Post"."threadId", "public"."Post"."rootPostId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1) OFFSET $2
0 / 1
SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."updatedAt", "public"."Post"."ipAddress", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."bodyHtml", "public"."Post"."bodyMd", "public"."Post"."bannedForThisPost", "public"."Post"."sage", "public"."Post"."threadId", "public"."Post"."rootPostId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1,$2,$3,$4) OFFSET $5
0 / 4
SELECT "public"."Thread"."id", "public"."Thread"."createdAt", "public"."Thread"."updatedAt", "public"."Thread"."bumpedAt", "public"."Thread"."title", "public"."Thread"."boardId", "public"."Thread"."rootPostId", "public"."Thread"."views", "public"."Thread"."sticky", "public"."Thread"."anchored", "public"."Thread"."locked", "public"."Thread"."cycle", "public"."Thread"."archived", "public"."Thread"."willArchive" FROM "public"."Thread" WHERE ("public"."Thread"."archived" = $1 AND "public"."Thread"."sticky" = $2 AND "public"."Thread"."boardId" = $3) ORDER BY "public"."Thread"."bumpedAt" DESC LIMIT $4 OFFSET $5
starchan-nginx     | 172.23.0.1 - - [03/Sep/2021:12:59:10 +0000] "GET /threads/k/latest?take=20 HTTP/1.1" 304 0 "https://www.starchan.local/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0" "-"
[12:59:10.798] INFO (starchan-server/2721 on 5e83dfdc8576): GET /threads/k/latest?take=20 304 99.65 ms - -
SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."updatedAt", "public"."Post"."ipAddress", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."bodyHtml", "public"."Post"."bodyMd", "public"."Post"."bannedForThisPost", "public"."Post"."sage", "public"."Post"."threadId", "public"."Post"."rootPostId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1,$2,$3) OFFSET $4
0 / 3
SELECT "public"."Post"."id", "public"."Post"."createdAt", "public"."Post"."updatedAt", "public"."Post"."ipAddress", "public"."Post"."name", "public"."Post"."authorId", "public"."Post"."tripcode", "public"."Post"."bodyHtml", "public"."Post"."bodyMd", "public"."Post"."bannedForThisPost", "public"."Post"."sage", "public"."Post"."threadId", "public"."Post"."rootPostId", "public"."Post"."boardId", "public"."Post"."userId" FROM "public"."Post" WHERE "public"."Post"."id" = $1 LIMIT $2 OFFSET $3
SELECT "public"."_FileToPost"."B", "public"."_FileToPost"."A" FROM "public"."_FileToPost" WHERE "public"."_FileToPost"."B" IN ($1)
SELECT "public"."File"."id", "public"."File"."createdAt", "public"."File"."updatedAt", "public"."File"."filename", "public"."File"."mimetype", "public"."File"."size", "public"."File"."nsfw" FROM "public"."File" WHERE "public"."File"."id" IN ($1,$2) OFFSET $3
